name: Black check

on: [push,pull_request]

jobs:
  black:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: 3.11.0
    - name: Black Check
      uses: jpetrucciani/black-check@master
